name: ConfigurateExample
main: io.tofpu.configurateprojectexample.ExamplePlugin
version: 1.0.0
commands:
  example:
    usage: "Usage: /example [get|set] [number|string|listOfStrings|spawn] [newValue]"
